config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'グルメ' },
    { id: 3, name: '観光スポット' },
    { id: 4, name: 'イベント' },
    { id: 5, name: '宿泊' },
    { id: 6, name: 'お土産' },
    { id: 7, name: '歴史'},
    { id: 8, name: '温泉'},
    { id: 9, name: 'その他' },
  ]
 
   include ActiveHash::Associations
   has_many :tweets
 
  end

app/models/city.rb
class City < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '岩国市' },
    { id: 3, name: '宇部市' },
    { id: 4, name: '下松市' },
    { id: 5, name: '山陽小野田市' },
    { id: 6, name: '周南市' },
    { id: 7, name: '下関市' },
    { id: 8, name: '周防大島町' },
    { id: 9, name: '長門市' },
    { id: 10, name: '美祢市' },
    { id: 11, name: '萩市' },
    { id: 12, name: '光市' },
    { id: 13, name: '防府市' },
    { id: 14, name: '柳井市' },
    { id: 15, name: '山口市' },
    { id: 16, name: '和木町・上関町・田布施町・平生町・阿武町' }
  ]

  include ActiveHash::Associations
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :city


  with_options numericality: { other_than: 1, message: "can't be blank" } do
    validates :category_id
    validates :city_id
  end

  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :text, length: { maximum: 1000 }
    validates :image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    # NAME_REGEX = /\A[ぁ-んァ-ン一-龥]/.freeze
    # PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze

    validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[nickname])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]


  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweets = Tweet.new
  end

  def show
    @tweets = Tweet.find(params[:id])
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def create
    @tweets = Tweet.new(tweet_params)
    if @tweets.valid?
      @tweets.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:name, :image, :category_id, :city_id, :text).merge(user_id: current_user.id)
  end

    
  def  set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YamaguchiPr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">知っちょる</a></h1>
        <% if user_signed_in? %>
          <div class = "user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %>
                  <%# マイページのリンクの設定。プルダウンで表示する %>
                </li>
              </ul>
            </span>
            <%= link_to "投稿する", new_tweet_path, class: "post" %> 
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
    </div>
  </header>
    <%= yield %>
  <script>
    $(function() {
      setTimeout(function(){
        $('.start p').fadeIn(1600);
      },0250); //0.5秒後にロゴをフェードイン!
      setTimeout(function(){
        $('.start').fadeOut(500);
      },2500); //2.5秒後にロゴ含め真っ白背景をフェードアウト！
    });
  </script>
  </body>


</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/tweets/index.html.erb
  <%# トップページ角島大橋 %>
      <div class="start">
        <p><img src="../../assets/tunoshimaohashi-image.png" alt=""></p>
      </div>
  <%# トップページ角島大橋 %>

  <%#検索フォーム%>
    <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "\uF002", class: "search-btn" %>
    <% end %>
  <%# 検索フォーム%>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      山口県の魅力を知ろう
    </h2>
    <p class='service-explain'>
      歴史を振り返ればわかるように、原動力をもたらす場所、
    </p>
    <p class='service-explain'>
      山口県は新たなパワーを生み出す場所です。
    </p>
  </div>
  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>

<%# 投稿一覧 %>
  <div class='tweet-contents'>
    <h2 class='title'>投稿一覧</h2>
     <%= link_to '新規投稿商品', new_tweet_path, class: "subtitle" %>
      <ul class='tweet-lists'>
      <% @tweets.each do |tweet| %>
        <li class='tweet-list'>
        <%= link_to tweet_path(tweet.id), method: :get do %>
          <div class='tweet-img-content'>
            <%= image_tag tweet.image, class: "tweet-img" %>
          </div>
        <% end %>
          <h2 class="tweet-name">
          <%= tweet.name %>
          </h2>
        </li>
      <% end %>
      </ul>
  </div>
  <%# /投稿一覧 %>

app/views/tweets/new.html.erb
<div class="tweets-sell-contents">
  <div class="tweets-sell-main">
    <h2 class="tweets-sell-title">情報を入力</h2>
    <%= form_with model: @tweets, url: tweets_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %> 

    <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"tweet-image", class: "image-select" %>
      </div>
    </div>
    <%# /画像 %>
    <%# 場所名と説明 %>
    <div class="new-tweets">
      <div class="weight-bold-text">
        名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"tweets-text", id:"name", placeholder:"名前（必須 40文字まで)（店名、観光地、イベント名など）", maxlength:"40" %>
      <div class="tweets-explain">
        <div class="weight-bold-text">
          おすすめポイント
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"tweets-text", id:"text", placeholder:"詳細（必須 1,000文字まで）(例）8月に下関市の花火大会に行きました。花火の数が多く迫力満点です" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /場所名と説明 %>

    <%# おすすめの詳細 %>
    <div class="tweets-detail">
      <div class="weight-bold-text">観光の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category", id:"tweet-category"}) %>
          <div class="weight-bold-text">
            市町村
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:city_id, City.all, :id, :name, {}, {class:"city", id:"tweet-status"}) %>
        </div>
      </div>
    </div>
    <%# /下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する", class:"sell-btn" %><br />
      <%= link_to '戻る', root_path, class:"back-btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<%# 投稿の概要 %>
  <div class="tweet-show">
    <div class="tweet-box">
      <h2 class="name">
        <%= @tweets.name %>
      </h2>
      <div class='tweet-img-content'>
        <%= image_tag @tweets.image ,class:"tweet-box-img" %>
      </div>


      <%# ログインしているユーザーと投稿しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
      <% if user_signed_in? %>
        <% if current_user.id == @tweets.user_id %>
          <%= link_to '投稿の編集', edit_tweet_path(@tweets.id), method: :get, class: "tweet-red-btn" %>
          <p class='or-text'>or</p>
          <%= link_to '削除', tweet_path(@tweets.id), method: :delete, class:'tweet-destroy' %>
        
        <% end %>
      <% end %>


      <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-tweet">投稿者</th>
            <td class="detail-value"><%= @tweets.user.nickname %></td>
          </tr>
          <tr>
            <th class="detail-tweet">投稿内容</th>
            <td class="detail-value"><%= @tweets.text %></td>
          </tr>
          <tr>
            <th class="detail-tweet">カテゴリー</th>
            <td class="detail-value"><%= @tweets.category.name %></td>
          </tr>
          <tr>
            <th class="detail-tweet">地域名</th>
            <td class="detail-value"><%= @tweets.city.name %></td>
          </tr>
          <tr>
        </tbody>
      </table>
      <div class="option">
        <div class="favorite-btn">
          <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
          <span>お気に入り 0</span>
        </div>
        <div class="report-btn">
          <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
          <span>不適切な投稿の通報</span>
        </div>
      </div>
    </div>
    <%# /投稿の概要 %>
    <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%# <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%> 
        <span>コメントする<span>
      </button>
    </form>
    </div>
    <div class="links">
      <a href="#" class="change-item-btn">
        ＜ 前の商品
      </a>
      <a href="#" class="change-item-btn">
        後ろの商品 ＞
      </a>
    </div>
    <a href="#" class='another-item'><%= @tweets.category.name %>をもっと見る</a>
  </div>